sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install: npm install -g gulp
install: npm install
after_success: CODECLIMATE_REPO_TOKEN=9338786ef61d320210d94fa289f33d566f3c1a111a38c9e96acdb4c77493d363 codeclimate-test-reporter < coverage/lcov.info